[project]
name = "slack-search-mcp"
version = "0.1.0"
dependencies = [
    "shared",
    "mcp[fastapi]>=2.2.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
    "google-cloud-bigquery>=3.45.2",
    "google-genai>=2.24.0",
    "python-dotenv>=1.2.3",
    "slack-sdk>=3.44.1",
    "google-auth>=2.58.0"
]

[tool.setuptools]
package-dir = {"" = "."}
packages = []
