[project]
name = "slack-search-mcp"
version = "0.1.0"
dependencies = [
    "shared",
    "mcp[fastapi]>=2.1.1",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
    "google-cloud-bigquery>=3.44.0",
    "google-genai>=2.20.0",
    "python-dotenv>=1.2.3",
    "slack-sdk>=3.44.0",
    "google-auth>=2.57.0"
]

[tool.setuptools]
package-dir = {"" = "."}
packages = []
