[project]
name = "aibot-logic"
version = "0.1.0"
dependencies = [
    "shared",
    "google-adk>=2.8.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
    "google-cloud-pubsub>=2.39.2",
    "google-cloud-firestore>=2.29.0",
    "slack-sdk>=3.43.0",
    "python-dotenv>=1.2.3",
    "mcp[fastapi]>=2.1.1",
    "vertexai>=1.71.1",
    "google-cloud-aiplatform>=2.0.1",
    "pydantic>=2.13.5",
    "pytz>=2026.3.post1",
    "pyjwt>=2.13.0"
]

[tool.setuptools]
package-dir = {"" = "."}
packages = []
