# Shared Internal Library
# Use submodules directly for imports to avoid circular dependencies:
# from shared.gcp_api import ...
# from shared.slack_api import ...
# from shared.firestore_api import ...
# from shared.security import ...
